language: python
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- nvm install
- npm install
- pip install wrangler
script: npm run test:ci
branches:
  except:
  - master
notifications:
  email: false
  slack:
    rooms:
      secure: iF5iLzwQ73WSWW3xIRV/hAWA2ZmMVsoXU6iNXOYFFisNmvTKS8eTWcha07pJuPrLqjwcCj8W036GrszeK/+Y6pB2Ta+k2EuesakWQeLayCfCSsG4RZOfGtjIvxeTzYEyyKd4Y+n0I53WviFpsQdb3x2XCWKMgojpHVwOCGPX05qN2Jxig2NIE/HYtnfek1w2we779x9d7fWZsWqUt3/95sVUdHGMqjuroSHEPSFjsFgFZl4xODDNei0JK2PqdPbdf80Nec/71BKwVYhsLI69+TAdcOK78YLBRb3Yw7l3XeSB8/pUXunbXP1pNbkY0oVpi2PkzztwcT4nZtGXEyhRNvaf4adKfpmu40zQTAuukMxYcwwUQ+7DTxqv+TrlRwJsLUpIghWBJZPt8nkqT4VcY0hCGG1r+YXsrgmoiw+e7UB3XAD8YLNen98UgD/YEcKbB+uMrHGggCp1VR/w8K6UJxNi4YR43RnxKyE8qY3e2q0wC1HH+wsSPLRCF0Ai2wYrWDGgPXPYQBgMGbFm9s2pbwsCBWBdMsSPZhi98s6BQCDIQRNtYZD6zzZ45T3lWxxgnqLamJLi6uCM6vo23/f4QAlSpv7yqz5scwCo60DGKIwWM7nUAjspoh7QP6Fmusotobr5idgKAikI43Wo7N5pDanKPVjVVuVXFlxMZx3P2pg=
deploy:
  provider: script
  script: npm run deploy:force
  on:
    branch: deploy/production
env:
  global:
    secure: NRL9vKqtjS1oA5xCzCplxDD/T6rNBGtUHEjuf9HRXkuLpULetOxMlLT1dY8900fNOgf1onKttiH/rMx2rmF4+sRCGVZWo4ycPU5hGwL3yj8bQeny+pxqFQWBrk7Qj0KHBXFzp5Nn//CIPnoSw0Il2c8Scop/q4IkzEkG4WwscWQCiggLGzKDjhe36tibm47dgp92sdvcvJuBt8cVhKHTfFXNySGRPZpeFgOgR6jTLgJve3ggTWWGrnH2yi5BZs/++eYY0L6eiGYHWVQxTJ3XtQfpQAqCcBcaSdmY822BPmqL3n9FbMlnM7Ce9hMew4sjNHzxUxHiJKEU6Dh+duRKUAQOSk9UnCPdYMCtErTVjdmOegfRMlDMHjz2fc6kC8wdunS5CWSmHebTW++a1gN6p/1eds6tFrQ34QZynE/e7y6TBzzohOPuAlVDHPb+EQdylfCWTnuFojDFRIPu5tYVYM/b0fcukxrP3+159eZZp+sGdVHsTh23qoPHdtlHY+SN8xarS97M/AePK/UNYhIrCJjOYYjm9vLe4ysNxmumfKOaoaCCiNydsAcjwR19EpotDe8ZfgVstaGKbXVLfO0Gvzz9DnCCcqE9OTXMH0KrRSTQFXlI3QU/uwk/pStdvsc36U6GxKhkW/SWWDvoqjKI0vvbDdUF/kAWZ2wYjh8ZdGc=
