language: python
cache:
  pip: true
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- nvm install
- npm install
- pip install wrangler
script: npm run test:ci
branches:
  except:
  - master
notifications:
  email: false
  slack:
    rooms:
      secure: iF5iLzwQ73WSWW3xIRV/hAWA2ZmMVsoXU6iNXOYFFisNmvTKS8eTWcha07pJuPrLqjwcCj8W036GrszeK/+Y6pB2Ta+k2EuesakWQeLayCfCSsG4RZOfGtjIvxeTzYEyyKd4Y+n0I53WviFpsQdb3x2XCWKMgojpHVwOCGPX05qN2Jxig2NIE/HYtnfek1w2we779x9d7fWZsWqUt3/95sVUdHGMqjuroSHEPSFjsFgFZl4xODDNei0JK2PqdPbdf80Nec/71BKwVYhsLI69+TAdcOK78YLBRb3Yw7l3XeSB8/pUXunbXP1pNbkY0oVpi2PkzztwcT4nZtGXEyhRNvaf4adKfpmu40zQTAuukMxYcwwUQ+7DTxqv+TrlRwJsLUpIghWBJZPt8nkqT4VcY0hCGG1r+YXsrgmoiw+e7UB3XAD8YLNen98UgD/YEcKbB+uMrHGggCp1VR/w8K6UJxNi4YR43RnxKyE8qY3e2q0wC1HH+wsSPLRCF0Ai2wYrWDGgPXPYQBgMGbFm9s2pbwsCBWBdMsSPZhi98s6BQCDIQRNtYZD6zzZ45T3lWxxgnqLamJLi6uCM6vo23/f4QAlSpv7yqz5scwCo60DGKIwWM7nUAjspoh7QP6Fmusotobr5idgKAikI43Wo7N5pDanKPVjVVuVXFlxMZx3P2pg=
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy:ci
  on:
    branch: deploy/production
env:
  global:
  - secure: M4NSa7sQ07AU3F3EuVviIb8zY4FEcqGiT3Uz/NJ9+ROvauthzPbX6abTMo2ALIHT963fnt32pAXqeZBDZPwOhWTxT7O8pXdjl/mGPmILQrBS5rgLHd53FYzgN6NsLPq/qwhRysTTR9zc5V7b0AoFgnXmp2/kICYEdBYLyXPayIl6KEGl5pHJqGM+oFVTlSP6gn64ufuRf868B+8rs8LXGH3k44u0DRr88a4kbXOa8TbVAqjdx73FC0vRBnmuOq/rBCtkxaqpVMb9i2FFRZ/u1y4n1KnrnJsKsjyBTBxfc4KOv8O+jRmTayaZG9pT4kxgiPGmlOBmxD5uXl2irYPmPDuy0+VAgCS2JRCPvHYjFy21goAAyaGkwhWCi+NA5pUfcmMSPmoNaY7ckGFBGZinDfOR0wErmtJ6Sf9yhLQTFpDg22bQHtkADTzxxHH8bKLTNeAgaVuOCz1QF6mK1U3QhzXQrQZqtm0s0Q8CAaw0j5SYST2lvamCi9vapOGrOpkvM8fmkcCVjiysGrYe/AWMfYwiIES0pSpwt8k9twrX6IdKOaaBZ/uO1cPCmoKpku4SCVGGIReIl/Up20I9Pa33vtysq9guW9F/JuE94JLR7G5ACUAXaDLmNshXoAYhU8UHiXDkynVtZ0GtFWCKcEwEPKl9GBlREMdzJrhDx1DrYEY=
