language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
  - npm install
  - pip install wrangler
script: npm run test:ci
notifications:
  email: false
  slack:
    rooms:
      secure: iF5iLzwQ73WSWW3xIRV/hAWA2ZmMVsoXU6iNXOYFFisNmvTKS8eTWcha07pJuPrLqjwcCj8W036GrszeK/+Y6pB2Ta+k2EuesakWQeLayCfCSsG4RZOfGtjIvxeTzYEyyKd4Y+n0I53WviFpsQdb3x2XCWKMgojpHVwOCGPX05qN2Jxig2NIE/HYtnfek1w2we779x9d7fWZsWqUt3/95sVUdHGMqjuroSHEPSFjsFgFZl4xODDNei0JK2PqdPbdf80Nec/71BKwVYhsLI69+TAdcOK78YLBRb3Yw7l3XeSB8/pUXunbXP1pNbkY0oVpi2PkzztwcT4nZtGXEyhRNvaf4adKfpmu40zQTAuukMxYcwwUQ+7DTxqv+TrlRwJsLUpIghWBJZPt8nkqT4VcY0hCGG1r+YXsrgmoiw+e7UB3XAD8YLNen98UgD/YEcKbB+uMrHGggCp1VR/w8K6UJxNi4YR43RnxKyE8qY3e2q0wC1HH+wsSPLRCF0Ai2wYrWDGgPXPYQBgMGbFm9s2pbwsCBWBdMsSPZhi98s6BQCDIQRNtYZD6zzZ45T3lWxxgnqLamJLi6uCM6vo23/f4QAlSpv7yqz5scwCo60DGKIwWM7nUAjspoh7QP6Fmusotobr5idgKAikI43Wo7N5pDanKPVjVVuVXFlxMZx3P2pg=
